[metadata.heroku]
  root-package = "github.com/republicprotocol/proxy-heroku-go"
  install = "./cmd/proxy"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[prune]
  go-tests = true
  unused-packages = true
